# Generated by Django 2.0.5 on 2018-05-11 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(default=0, verbose_name="up's count")),
                ('down', models.IntegerField(default=0, verbose_name="down's count")),
            ],
        ),
        migrations.AlterField(
            model_name='auther',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 11, 14, 11, 26, 935900, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
