# Generated by Django 2.0.5 on 2018-05-11 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180511_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 11, 14, 23, 54, 970439, tzinfo=utc), null=True),
        ),
    ]
