# Generated by Django 2.0.5 on 2018-05-11 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180511_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 11, 14, 29, 16, 94223, tzinfo=utc), null=True),
        ),
    ]
