# Generated by Django 2.0.5 on 2018-05-11 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180511_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='discussion title')),
                ('body', models.TextField(blank=True, max_length=1280, verbose_name='discussion')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1280, verbose_name='reply')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='books.Discuss')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='discuss',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='books.Book'),
        ),
    ]
