# Generated by Django 2.0.5 on 2018-05-19 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Content', '0002_auto_20180519_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='discussion title')),
                ('body', models.TextField(blank=True, max_length=1280, verbose_name='discussion')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions',
                                           to='Content.Book')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1280, verbose_name='reply')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys',
                                              to='Discussion.Discuss')),
            ],
        ),
    ]
