# Generated by Django 2.0.5 on 2018-06-13 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='讨论标题')),
                ('body', models.TextField(blank=True, max_length=1280, verbose_name='讨论正文')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': '书籍讨论',
                'verbose_name_plural': '书籍讨论',
            },
        ),
        migrations.CreateModel(
            name='DiscussReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1280, verbose_name='回复正文')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys',
                                              to='Discussion.Discuss')),
                ('reply_to',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys',
                                   to='Discussion.DiscussReply')),
            ],
            options={
                'verbose_name': '讨论回复',
                'verbose_name_plural': '讨论回复',
            },
        ),
    ]
