# Generated by Django 2.1.5 on 2022-11-21 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='讨论标题')),
                ('body', models.TextField(blank=True, max_length=1280, verbose_name='讨论正文')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': '书籍讨论',
                'verbose_name_plural': '书籍讨论',
            },
        ),
        migrations.CreateModel(
            name='DiscussReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1280, verbose_name='回复正文')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': '讨论回复',
                'verbose_name_plural': '讨论回复',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否阅读')),
                ('is_reply', models.BooleanField(default=False, verbose_name='是否是回复')),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='Discussion.Discuss', verbose_name='主题')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ('-create_time',),
            },
        ),
    ]
