# Generated by Django 2.0.5 on 2018-05-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discuss',
            options={'verbose_name': '书籍讨论', 'verbose_name_plural': '书籍讨论'},
        ),
        migrations.AlterModelOptions(
            name='discussreply',
            options={'verbose_name': '讨论回复', 'verbose_name_plural': '讨论回复'},
        ),
        migrations.AddField(
            model_name='discussreply',
            name='parent_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_replys',
                                    to='Discussion.DiscussReply'),
        ),
        migrations.AddField(
            model_name='discussreply',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys',
                                    to='Discussion.DiscussReply'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='body',
            field=models.TextField(blank=True, max_length=1280, verbose_name='讨论正文'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='title',
            field=models.CharField(max_length=128, verbose_name='讨论标题'),
        ),
        migrations.AlterField(
            model_name='discussreply',
            name='body',
            field=models.TextField(max_length=1280, verbose_name='回复正文'),
        ),
    ]
