# Generated by Django 2.0.5 on 2018-06-13 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Content', '0001_initial'),
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discuss',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions',
                                    to='Content.Book'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
