# Generated by Django 2.0.5 on 2018-09-06 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Discussion', '0002_auto_20180613_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussreply',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='discussreply',
            name='reply_to',
            field=models.ManyToManyField(related_name='replys_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
