# Generated by Django 2.0.5 on 2018-05-29 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Discussion', '0003_auto_20180529_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussreply',
            name='parent_reply',
        ),
    ]
