# Generated by Django 2.0.5 on 2018-09-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0005_auto_20180906_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
