# Generated by Django 2.0.5 on 2018-09-07 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0007_auto_20180907_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('create_time',), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期'),
        ),
    ]
