# Generated by Django 2.0.5 on 2018-09-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0008_auto_20180907_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-create_time',), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.RenameField(
            model_name='discussreply',
            old_name='reply_to',
            new_name='mentions',
        ),
    ]
