# Generated by Django 2.0.5 on 2018-09-08 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Discussion', '0009_auto_20180908_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='mentions',
            field=models.ManyToManyField(related_name='replys_from_discussion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussreply',
            name='mentions',
            field=models.ManyToManyField(related_name='replys_from_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
