# Generated by Django 2.0.5 on 2018-09-08 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0010_auto_20180908_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='instance',
        ),
        migrations.AddField(
            model_name='notification',
            name='discuss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='Discussion.Discuss', verbose_name='主题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='Discussion.DiscussReply', verbose_name='回复'),
        ),
    ]
