# Generated by Django 2.0.5 on 2018-06-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Discussion', '0002_auto_20180613_1819'),
        ('Content', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user',
                                       to='User.UserCollection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercollection',
            name='books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    related_name='collection_users', to='Content.Book'),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='discussions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    related_name='collection_users', to='Discussion.Discuss'),
        ),
    ]
