# Generated by Django 2.0.5 on 2018-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Discussion', '0002_auto_20180613_1819'),
        ('Content', '0001_initial'),
        ('User', '0003_auto_20180613_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='books',
        ),
        migrations.AddField(
            model_name='usercollection',
            name='books',
            field=models.ManyToManyField(null=True, related_name='collection_users', to='Content.Book'),
        ),
        migrations.RemoveField(
            model_name='usercollection',
            name='discussions',
        ),
        migrations.AddField(
            model_name='usercollection',
            name='discussions',
            field=models.ManyToManyField(null=True, related_name='collection_users', to='Discussion.Discuss'),
        ),
    ]
