# Generated by Django 2.0.5 on 2018-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('User', '0004_auto_20180613_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='books',
            field=models.ManyToManyField(related_name='collection_users', to='Content.Book'),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='discussions',
            field=models.ManyToManyField(related_name='collection_users', to='Discussion.Discuss'),
        ),
    ]
