# Generated by Django 2.1.1 on 2022-11-21 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='作者名')),
                ('about', models.TextField(blank=True, max_length=1280, verbose_name='关于作者')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书籍名称')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='出版日期')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('intro', models.TextField(blank=True, max_length=1280, verbose_name='简介')),
                ('cover', models.ImageField(blank=True, default='book_cover/default.jpg', upload_to='book_cover/%Y/%m/%d', verbose_name='封面')),
                ('viewing', models.IntegerField(default=0, verbose_name='查看数')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Content.Auther')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carousel/%Y/%d/%d', verbose_name='滚动图')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='图片名字')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='展示标题')),
                ('intro', models.TextField(blank=True, max_length=128, verbose_name='展示介绍')),
                ('link', models.URLField(blank=True, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '滚动图',
                'verbose_name_plural': '滚动图',
            },
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='出版社名')),
                ('establish_date', models.DateField(blank=True, null=True, verbose_name='创建日期')),
                ('about', models.TextField(blank=True, max_length=1024, verbose_name='关于出版社')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '书籍标签',
                'verbose_name_plural': '书籍标签',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Content.Publishing'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='Content.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'auther')},
        ),
    ]
