# Generated by Django 2.0.5 on 2018-05-19 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='book',
        ),
        migrations.RemoveField(
            model_name='discussreply',
            name='discuss',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pub_date']},
        ),
        migrations.DeleteModel(
            name='Discuss',
        ),
        migrations.DeleteModel(
            name='DiscussReply',
        ),
    ]
