# Generated by Django 2.0.5 on 2018-05-20 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0002_auto_20180519_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishing',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auther',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='auther name'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='publishing name'),
        ),
    ]
