# Generated by Django 2.0.5 on 2018-05-21 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0003_auto_20180520_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='age',
        ),
    ]
