# Generated by Django 2.0.5 on 2018-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0004_remove_auther_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='location',
        ),
        migrations.AddField(
            model_name='auther',
            name='about',
            field=models.TextField(blank=True, max_length=1280),
        ),
    ]
