# Generated by Django 2.0.5 on 2018-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0005_auto_20180521_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='about',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='publishing',
            name='establish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
