# Generated by Django 2.0.5 on 2018-05-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0006_auto_20180521_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carousel/', verbose_name='滚动图', width_field=720)),
                ('name', models.CharField(max_length=32, verbose_name='图片名')),
            ],
        ),
    ]
