# Generated by Django 2.0.5 on 2018-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0007_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to='carousel/', verbose_name='滚动图'),
        ),
    ]
