# Generated by Django 2.0.5 on 2018-05-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0009_auto_20180524_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='图片名'),
        ),
    ]
