# Generated by Django 2.0.5 on 2018-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0010_auto_20180524_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to='carousel/%Y/%d/%d', verbose_name='滚动图'),
        ),
    ]
