# Generated by Django 2.0.5 on 2018-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0011_auto_20180524_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='book_cover/default.jpg', upload_to='book_cover/%Y/%m/%d',
                                    verbose_name='书籍封面'),
        ),
    ]
