# Generated by Django 2.0.5 on 2018-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Content', '0013_auto_20180525_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='viewing',
            field=models.IntegerField(default=0, verbose_name='查看数'),
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
